name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Download the Rust binary
      uses: actions/download-artifact@v3
      with:
        name: lunchbot
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)