name: Rust and Docker testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust_docker_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build Rust binary
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Archive Rust binary

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)